"""add_all_data

Revision ID: 5b69bc8750a4
Revises: 80c879f86bc9
Create Date: 2026-01-21 12:33:27.359838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b69bc8750a4'
down_revision: Union[str, Sequence[str], None] = '7c31029a1d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""INSERT INTO car (id, brand, license_plate, load_capacity, body_type, fuel_consumption, created_at, updated_at, active) VALUES
(gen_random_uuid(), 'Volvo FH', 'A123BC77', 20.0, 'Рефрижератор', 32.5, NOW(), NOW(), true),
(gen_random_uuid(), 'MAN TGS', 'B456DE77', 18.5, 'Тентованный', 30.2, NOW(), NOW(), true),
(gen_random_uuid(), 'Scania R500', 'C789FG77', 22.0, 'Изотермический', 34.1, NOW(), NOW(), true),
(gen_random_uuid(), 'Mercedes Actros', 'D012GH77', 19.0, 'Цистерна', 31.8, NOW(), NOW(), true),
(gen_random_uuid(), 'DAF XF', 'E345IJ77', 21.5, 'Самосвал', 33.2, NOW(), NOW(), true),
(gen_random_uuid(), 'Renault Magnum', 'F678KL77', 17.5, 'Тентованный', 29.7, NOW(), NOW(), true),
(gen_random_uuid(), 'Iveco Stralis', 'G901MN77', 20.5, 'Рефрижератор', 32.0, NOW(), NOW(), true),
(gen_random_uuid(), 'Kamaz 5490', 'H234OP77', 23.0, 'Тентованный', 35.5, NOW(), NOW(), true),
(gen_random_uuid(), 'Maz 5440', 'J567QR77', 18.0, 'Цистерна', 30.8, NOW(), NOW(), true),
(gen_random_uuid(), 'Ford F-MAX', 'K890ST77', 19.5, 'Изотермический', 31.2, NOW(), NOW(), true),
(gen_random_uuid(), 'Volvo FM', 'L123UV77', 16.5, 'Тентованный', 28.5, NOW(), NOW(), true),
(gen_random_uuid(), 'MAN TGX', 'M456WX77', 22.5, 'Рефрижератор', 33.8, NOW(), NOW(), true),
(gen_random_uuid(), 'Scania G450', 'N789YZ77', 20.0, 'Тентованный', 32.1, NOW(), NOW(), true),
(gen_random_uuid(), 'Mercedes Atego', 'O012AB78', 15.0, 'Тентованный', 27.3, NOW(), NOW(), true),
(gen_random_uuid(), 'DAF CF', 'P345CD78', 17.0, 'Рефрижератор', 29.0, NOW(), NOW(), true),
(gen_random_uuid(), 'Iveco S-Way', 'Q678EF78', 19.8, 'Тентованный', 32.4, NOW(), NOW(), true),
(gen_random_uuid(), 'Kamaz 6520', 'R901GH78', 25.0, 'Самосвал', 38.0, NOW(), NOW(), true),
(gen_random_uuid(), 'Maz 6430', 'S234IJ78', 16.8, 'Изотермический', 29.5, NOW(), NOW(), true),
(gen_random_uuid(), 'Volvo FE', 'T567KL78', 14.5, 'Тентованный', 26.8, NOW(), NOW(), true),
(gen_random_uuid(), 'MAN TGL', 'U890MN78', 13.0, 'Тентованный', 25.2, NOW(), NOW(), true);""")
    # ### end Alembic commands ###
    op.execute("""INSERT INTO driver (id, full_name, license_number, license_category, experience_years, hire_date, car_id, created_at, updated_at, active) VALUES
(gen_random_uuid(), 'Иванов Иван Иванович', '77АВ123456', 'CE', 5, '2019-03-15', (SELECT id FROM car WHERE license_plate = 'A123BC77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Петров Петр Петрович', '77ВС789012', 'CE', 7, '2017-06-20', (SELECT id FROM car WHERE license_plate = 'B456DE77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Сидоров Алексей Викторович', '77DE345678', 'CE', 3, '2021-01-10', (SELECT id FROM car WHERE license_plate = 'C789FG77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Кузнецов Дмитрий Сергеевич', '77FG901234', 'CE', 10, '2014-08-05', (SELECT id FROM car WHERE license_plate = 'D012GH77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Смирнова Анна Олеговна', '77HI567890', 'C1E', 4, '2020-02-28', (SELECT id FROM car WHERE license_plate = 'E345IJ77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Васильев Михаил Андреевич', '77JK123456', 'CE', 8, '2016-04-12', (SELECT id FROM car WHERE license_plate = 'F678KL77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Новикова Екатерина Дмитриевна', '77LM789012', 'C1E', 2, '2022-07-30', (SELECT id FROM car WHERE license_plate = 'G901MN77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Морозов Сергей Владимирович', '77NO345678', 'CE', 12, '2012-09-18', (SELECT id FROM car WHERE license_plate = 'H234OP77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Волков Андрей Николаевич', '77PQ901234', 'CE', 6, '2018-05-22', (SELECT id FROM car WHERE license_plate = 'J567QR77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Алексеев Павел Игоревич', '77RS567890', 'CE', 9, '2015-11-14', (SELECT id FROM car WHERE license_plate = 'K890ST77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Лебедев Игорь Александрович', '77TU123456', 'C1E', 5, '2019-10-08', (SELECT id FROM car WHERE license_plate = 'L123UV77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Соколова Мария Петровна', '77VW789012', 'CE', 4, '2020-03-25', (SELECT id FROM car WHERE license_plate = 'M456WX77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Козлов Артем Витальевич', '77XY345678', 'CE', 11, '2013-07-19', (SELECT id FROM car WHERE license_plate = 'N789YZ77'), NOW(), NOW(), true),
(gen_random_uuid(), 'Павлов Денис Олегович', '77ZA901234', 'C1E', 3, '2021-12-03', (SELECT id FROM car WHERE license_plate = 'O012AB78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Семенов Виктор Иванович', '77AB567890', 'CE', 7, '2017-02-17', (SELECT id FROM car WHERE license_plate = 'P345CD78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Голубева Ольга Сергеевна', '77BC123456', 'C1E', 6, '2018-08-09', (SELECT id FROM car WHERE license_plate = 'Q678EF78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Киселев Николай Дмитриевич', '77CD789012', 'CE', 15, '2009-04-26', (SELECT id FROM car WHERE license_plate = 'R901GH78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Макаров Евгений Андреевич', '77EF345678', 'CE', 8, '2016-06-11', (SELECT id FROM car WHERE license_plate = 'S234IJ78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Захаров Роман Викторович', '77GH901234', 'C1E', 4, '2020-09-23', (SELECT id FROM car WHERE license_plate = 'T567KL78'), NOW(), NOW(), true),
(gen_random_uuid(), 'Борисов Антон Павлович', '77IJ567890', 'CE', 9, '2015-01-31', (SELECT id FROM car WHERE license_plate = 'U890MN78'), NOW(), NOW(), true);
""")

    op.execute("""INSERT INTO tariff (id, price_per_km, cargo_type, min_price, date_start, date_end, created_at, updated_at, active) VALUES
(gen_random_uuid(), 45.50, 'Продовольствие', 5000.00, '2024-01-01', '2024-12-31', NOW(), NOW(), true),
(gen_random_uuid(), 52.30, 'Строительные материалы', 6500.00, '2024-01-01', '2024-12-31', NOW(), NOW(), true),
(gen_random_uuid(), 67.80, 'Нефтепродукты', 8500.00, '2024-01-01', '2024-06-30', NOW(), NOW(), true),
(gen_random_uuid(), 75.20, 'Химикаты', 9500.00, '2024-01-01', '2024-12-31', NOW(), NOW(), true),
(gen_random_uuid(), 38.90, 'Товары народного потребления', 4200.00, '2024-01-01', NULL, NOW(), NOW(), true),
(gen_random_uuid(), 89.50, 'Опасные грузы', 12000.00, '2024-01-01', '2024-12-31', NOW(), NOW(), true),
(gen_random_uuid(), 42.10, 'Рефрижераторные грузы', 5500.00, '2024-01-01', NULL, NOW(), NOW(), true),
(gen_random_uuid(), 31.50, 'Сельхозпродукция', 3500.00, '2024-03-01', '2024-10-31', NOW(), NOW(), true),
(gen_random_uuid(), 58.70, 'Металлопрокат', 7200.00, '2024-01-01', '2024-12-31', NOW(), NOW(), true),
(gen_random_uuid(), 49.80, 'Электроника', 6100.00, '2024-01-01', NULL, NOW(), NOW(), true);""")


    op.execute("""INSERT INTO route (id, origin, destination, distance_km, avg_time_hours, road_type, created_at, updated_at, active) VALUES
(gen_random_uuid(), 'Москва', 'Санкт-Петербург', 710.0, 10.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Москва', 'Нижний Новгород', 420.0, 6.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Москва', 'Казань', 815.0, 12.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Москва', 'Ростов-на-Дону', 1075.0, 15.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Москва', 'Екатеринбург', 1800.0, 25.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Санкт-Петербург', 'Москва', 710.0, 10.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Санкт-Петербург', 'Псков', 290.0, 4.5, 'Региональная', NOW(), NOW(), true),
(gen_random_uuid(), 'Санкт-Петербург', 'Великий Новгород', 180.0, 3.0, 'Региональная', NOW(), NOW(), true),
(gen_random_uuid(), 'Казань', 'Уфа', 520.0, 7.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Казань', 'Самара', 350.0, 5.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Нижний Новгород', 'Чебоксары', 230.0, 3.5, 'Региональная', NOW(), NOW(), true),
(gen_random_uuid(), 'Нижний Новгород', 'Иваново', 270.0, 4.0, 'Региональная', NOW(), NOW(), true),
(gen_random_uuid(), 'Екатеринбург', 'Челябинск', 210.0, 3.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Екатеринбург', 'Тюмень', 325.0, 4.5, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Ростов-на-Дону', 'Краснодар', 270.0, 4.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Ростов-на-Дону', 'Волгоград', 480.0, 7.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Новосибирск', 'Омск', 640.0, 9.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Новосибирск', 'Кемерово', 260.0, 4.0, 'Региональная', NOW(), NOW(), true),
(gen_random_uuid(), 'Красноярск', 'Иркутск', 1060.0, 15.0, 'Магистраль', NOW(), NOW(), true),
(gen_random_uuid(), 'Владивосток', 'Хабаровск', 760.0, 11.0, 'Магистраль', NOW(), NOW(), true);""")


    op.execute("""INSERT INTO shipment (id, shipment_date, cargo_weight, status, car_id, driver_id, route_id, tariff_id, total_cost, created_at, updated_at, active) VALUES
(gen_random_uuid(), '2024-01-15 08:00:00', 15.5, 'delivered', 
 (SELECT id FROM car WHERE license_plate = 'A123BC77'),
 (SELECT id FROM driver WHERE license_number = '77АВ123456'),
 (SELECT id FROM route WHERE origin = 'Москва' AND destination = 'Санкт-Петербург'),
 (SELECT id FROM tariff WHERE cargo_type = 'Продовольствие'),
 15.5 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Продовольствие') * 710.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-01-20 10:30:00', 18.0, 'in_transit',
 (SELECT id FROM car WHERE license_plate = 'B456DE77'),
 (SELECT id FROM driver WHERE license_number = '77ВС789012'),
 (SELECT id FROM route WHERE origin = 'Москва' AND destination = 'Казань'),
 (SELECT id FROM tariff WHERE cargo_type = 'Строительные материалы'),
 18.0 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Строительные материалы') * 815.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-02-01 07:00:00', 12.3, 'pending',
 (SELECT id FROM car WHERE license_plate = 'C789FG77'),
 (SELECT id FROM driver WHERE license_number = '77DE345678'),
 (SELECT id FROM route WHERE origin = 'Санкт-Петербург' AND destination = 'Москва'),
 (SELECT id FROM tariff WHERE cargo_type = 'Рефрижераторные грузы'),
 12.3 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Рефрижераторные грузы') * 710.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-01-25 14:00:00', 22.0, 'delivered',
 (SELECT id FROM car WHERE license_plate = 'D012GH77'),
 (SELECT id FROM driver WHERE license_number = '77FG901234'),
 (SELECT id FROM route WHERE origin = 'Москва' AND destination = 'Ростов-на-Дону'),
 (SELECT id FROM tariff WHERE cargo_type = 'Нефтепродукты'),
 22.0 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Нефтепродукты') * 1075.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-02-05 09:15:00', 16.8, 'in_transit',
 (SELECT id FROM car WHERE license_plate = 'E345IJ77'),
 (SELECT id FROM driver WHERE license_number = '77HI567890'),
 (SELECT id FROM route WHERE origin = 'Екатеринбург' AND destination = 'Челябинск'),
 (SELECT id FROM tariff WHERE cargo_type = 'Металлопрокат'),
 16.8 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Металлопрокат') * 210.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-01-30 11:00:00', 14.2, 'delivered',
 (SELECT id FROM car WHERE license_plate = 'F678KL77'),
 (SELECT id FROM driver WHERE license_number = '77JK123456'),
 (SELECT id FROM route WHERE origin = 'Нижний Новгород' AND destination = 'Чебоксары'),
 (SELECT id FROM tariff WHERE cargo_type = 'Товары народного потребления'),
 14.2 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Товары народного потребления') * 230.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-02-10 06:30:00', 19.5, 'pending',
 (SELECT id FROM car WHERE license_plate = 'G901MN77'),
 (SELECT id FROM driver WHERE license_number = '77LM789012'),
 (SELECT id FROM route WHERE origin = 'Казань' AND destination = 'Уфа'),
 (SELECT id FROM tariff WHERE cargo_type = 'Химикаты'),
 19.5 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Химикаты') * 520.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-01-28 13:45:00', 21.0, 'cancelled',
 (SELECT id FROM car WHERE license_plate = 'H234OP77'),
 (SELECT id FROM driver WHERE license_number = '77NO345678'),
 (SELECT id FROM route WHERE origin = 'Москва' AND destination = 'Екатеринбург'),
 (SELECT id FROM tariff WHERE cargo_type = 'Опасные грузы'),
 21.0 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Опасные грузы') * 1800.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-02-03 08:20:00', 17.3, 'delivered',
 (SELECT id FROM car WHERE license_plate = 'J567QR77'),
 (SELECT id FROM driver WHERE license_number = '77PQ901234'),
 (SELECT id FROM route WHERE origin = 'Ростов-на-Дону' AND destination = 'Краснодар'),
 (SELECT id FROM tariff WHERE cargo_type = 'Сельхозпродукция'),
 17.3 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Сельхозпродукция') * 270.0,
 NOW(), NOW(), true),

(gen_random_uuid(), '2024-02-08 12:00:00', 13.7, 'in_transit',
 (SELECT id FROM car WHERE license_plate = 'K890ST77'),
 (SELECT id FROM driver WHERE license_number = '77RS567890'),
 (SELECT id FROM route WHERE origin = 'Новосибирск' AND destination = 'Омск'),
 (SELECT id FROM tariff WHERE cargo_type = 'Электроника'),
 13.7 * (SELECT price_per_km FROM tariff WHERE cargo_type = 'Электроника') * 640.0,
 NOW(), NOW(), true);""")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Очищаем таблицы в обратном порядке из-за внешних ключей
    op.execute("DELETE FROM shipment;")
    op.execute("DELETE FROM route;")
    op.execute("DELETE FROM tariff;")
    op.execute("DELETE FROM driver;")
    op.execute("DELETE FROM car;")