"""next 2

Revision ID: 6a7b765bd512
Revises: fd2b9635ba34
Create Date: 2026-01-18 22:52:58.273469

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7b765bd512'
down_revision: Union[str, Sequence[str], None] = 'fd2b9635ba34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Сначала добавляем описание к тарифу
    op.add_column('tariff', sa.Column('description', sa.String(length=500), nullable=True))

    # УДАЛЯЕМ ВНЕШНИЕ КЛЮЧИ перед изменением типа
    op.drop_constraint('shipment_tariff_id_fkey', 'shipment', type_='foreignkey')
    op.drop_constraint('route_tariff_tariff_id_fkey', 'route_tariff', type_='foreignkey')

    # Создаем временную последовательность для новых id
    op.execute("CREATE SEQUENCE IF NOT EXISTS tariff_id_seq")

    # Создаем временную колонку с INTEGER
    op.add_column('tariff', sa.Column('new_id', sa.Integer(), nullable=True))

    # Копируем данные с генерацией новых ID
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id FROM tariff ORDER BY date_start"))

    new_ids = {}
    for idx, row in enumerate(results, start=1):
        new_ids[str(row[0])] = idx

    # Обновляем новые ID в таблице tariff
    for old_id, new_id in new_ids.items():
        connection.execute(
            sa.text("UPDATE tariff SET new_id = :new_id WHERE id = :old_id"),
            {"new_id": new_id, "old_id": old_id}
        )

    # Обновляем shipment.tariff_id
    for old_id, new_id in new_ids.items():
        connection.execute(
            sa.text("UPDATE shipment SET tariff_id = :new_id WHERE tariff_id = :old_id"),
            {"new_id": new_id, "old_id": old_id}
        )

    # Обновляем route_tariff.tariff_id
    for old_id, new_id in new_ids.items():
        connection.execute(
            sa.text("UPDATE route_tariff SET tariff_id = :new_id WHERE tariff_id = :old_id"),
            {"new_id": new_id, "old_id": old_id}
        )

    # Делаем новые колонки NOT NULL
    op.alter_column('tariff', 'new_id', nullable=False)

    # Удаляем старый столбец id (теперь можно, т.к. внешние ключи удалены)
    op.drop_column('tariff', 'id')

    # Переименовываем new_id в id
    op.alter_column('tariff', 'new_id', new_column_name='id')

    # Устанавливаем как первичный ключ с автоинкрементом
    op.create_primary_key('pk_tariff', 'tariff', ['id'])
    op.execute("ALTER TABLE tariff ALTER COLUMN id SET DEFAULT nextval('tariff_id_seq')")

    # Изменяем тип shipment.tariff_id на INTEGER
    op.alter_column('shipment', 'tariff_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="tariff_id::text::integer")

    # Изменяем тип route_tariff.tariff_id на INTEGER
    op.alter_column('route_tariff', 'tariff_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="tariff_id::text::integer")

    # ВОССТАНАВЛИВАЕМ ВНЕШНИЕ КЛЮЧИ
    op.create_foreign_key('shipment_tariff_id_fkey', 'shipment', 'tariff', ['tariff_id'], ['id'])
    op.create_foreign_key('route_tariff_tariff_id_fkey', 'route_tariff', 'tariff', ['tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Сначала удаляем внешние ключи
    op.drop_constraint('shipment_tariff_id_fkey', 'shipment', type_='foreignkey')
    op.drop_constraint('route_tariff_tariff_id_fkey', 'route_tariff', type_='foreignkey')

    # Удаляем описание
    op.drop_column('tariff', 'description')

    # Создаем временную колонку UUID
    op.add_column('tariff', sa.Column('old_id', sa.UUID(), nullable=True))

    # Генерируем новые UUID для каждого тарифа
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id FROM tariff"))

    old_ids = {}
    for row in results:
        new_uuid = str(uuid.uuid4())
        old_ids[row[0]] = new_uuid

    # Обновляем shipment.tariff_id обратно на UUID
    for old_int_id, new_uuid in old_ids.items():
        connection.execute(
            sa.text("UPDATE shipment SET tariff_id = :new_uuid WHERE tariff_id = :old_id"),
            {"new_uuid": new_uuid, "old_id": old_int_id}
        )

    # Обновляем route_tariff.tariff_id обратно на UUID
    for old_int_id, new_uuid in old_ids.items():
        connection.execute(
            sa.text("UPDATE route_tariff SET tariff_id = :new_uuid WHERE tariff_id = :old_id"),
            {"new_uuid": new_uuid, "old_id": old_int_id}
        )

    # Обновляем временную колонку в tariff
    for old_int_id, new_uuid in old_ids.items():
        connection.execute(
            sa.text("UPDATE tariff SET old_id = :new_uuid WHERE id = :old_id"),
            {"new_uuid": new_uuid, "old_id": old_int_id}
        )

    # Делаем old_id NOT NULL
    op.alter_column('tariff', 'old_id', nullable=False)

    # Удаляем старый id и переименовываем
    op.drop_column('tariff', 'id')
    op.alter_column('tariff', 'old_id', new_column_name='id')

    # Устанавливаем как первичный ключ
    op.create_primary_key('pk_tariff', 'tariff', ['id'])

    # Удаляем последовательность
    op.execute("DROP SEQUENCE IF EXISTS tariff_id_seq")

    # Возвращаем типы обратно на UUID
    op.alter_column('shipment', 'tariff_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)

    op.alter_column('route_tariff', 'tariff_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)

    # Восстанавливаем внешние ключи
    op.create_foreign_key('shipment_tariff_id_fkey', 'shipment', 'tariff', ['tariff_id'], ['id'])
    op.create_foreign_key('route_tariff_tariff_id_fkey', 'route_tariff', 'tariff', ['tariff_id'], ['id'])

    # ### end Alembic commands ###