"""add_trigger_for_not_delete_shipment

Revision ID: 6e0961388656
Revises: 779d3e53a441
Create Date: 2026-01-21 01:05:34.398407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0961388656'
down_revision: Union[str, Sequence[str], None] = '779d3e53a441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем функцию для защиты таблиц от удаления
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_table_drop()
    RETURNS event_trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
        obj record;
    BEGIN
        FOR obj IN SELECT * FROM pg_event_trigger_dropped_objects()
        LOOP
            -- Запрещаем удаление таблицы shipment
            IF obj.object_type = 'table' AND obj.object_name = 'shipment' THEN
                RAISE EXCEPTION 'Удаление таблицы shipment запрещено!';
            END IF;

            -- Запрещаем удаление других важных таблиц
            IF obj.object_type = 'table' AND obj.object_name IN ('driver', 'car', 'route', 'tariff') THEN
                RAISE EXCEPTION 'Удаление таблицы % запрещено!', obj.object_name;
            END IF;
        END LOOP;
    END;
    $$;
    """)

    # Создаем event trigger
    op.execute("""
    DROP EVENT TRIGGER IF EXISTS prevent_important_drops;
    CREATE EVENT TRIGGER prevent_important_drops
        ON sql_drop
        EXECUTE FUNCTION prevent_table_drop();
    """)

    # Создаем вспомогательную функцию для проверки работы триггера
    op.execute("""
    CREATE OR REPLACE FUNCTION check_table_protection()
    RETURNS TABLE(
        table_name TEXT,
        is_protected BOOLEAN,
        trigger_exists BOOLEAN
    )
    LANGUAGE plpgsql
    AS $$
    BEGIN
        RETURN QUERY
        SELECT 
            t.table_name::TEXT,
            t.table_name IN ('shipment', 'driver', 'car', 'route', 'tariff') as is_protected,
            EXISTS (
                SELECT 1 FROM pg_event_trigger 
                WHERE evtname = 'prevent_important_drops'
            ) as trigger_exists
        FROM information_schema.tables t
        WHERE t.table_schema = 'public'
          AND t.table_type = 'BASE TABLE'
          AND t.table_name IN ('shipment', 'driver', 'car', 'route', 'tariff')
        ORDER BY t.table_name;
    END;
    $$;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем триггер
    op.execute("DROP EVENT TRIGGER IF EXISTS prevent_important_drops;")

    # Удаляем функцию
    op.execute("DROP FUNCTION IF EXISTS prevent_table_drop();")

    # Удаляем вспомогательную функцию
    op.execute("DROP FUNCTION IF EXISTS check_table_protection();")

    # ### end Alembic commands ###