"""delete cargo_type column

Revision ID: 779d3e53a441
Revises: 6ca311e13feb
Create Date: 2026-01-20 23:25:21.553561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779d3e53a441'
down_revision: Union[str, Sequence[str], None] = '6ca311e13feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'is_deleted')
    op.drop_column('car', 'deleted_at')
    op.drop_column('shipment', 'cargo_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('cargo_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
