"""next

Revision ID: fd2b9635ba34
Revises: 6c8ec95fe547
Create Date: 2026-01-18 21:59:48.484219

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2b9635ba34'
down_revision: Union[str, Sequence[str], None] = '6c8ec95fe547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Сначала добавляем новые колонки
    op.add_column('shipment', sa.Column('cargo_type', sa.String(length=50), nullable=False))
    op.add_column('shipment', sa.Column('total_cost', sa.Float(), nullable=True))

    # Для изменения типа id на UUID нужно использовать USING
    # Но сначала проверим, нужно ли вообще это изменение

    # ЗАКОММЕНТИРУЕМ или ИЗМЕНИМ эту строку:
    # op.alter_column('route_tariff', 'id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)

    # Вместо этого, если действительно нужно изменить на UUID, делаем так:
    # Создаем временную колонку, копируем данные, удаляем старую, переименовываем
    op.add_column('route_tariff', sa.Column('new_id', sa.Uuid(), nullable=True))

    # Генерируем UUID для существующих записей
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id FROM route_tariff"))
    for row in results:
        new_uuid = str(uuid.uuid4())
        connection.execute(
            sa.text("UPDATE route_tariff SET new_id = :new_uuid WHERE id = :old_id"),
            {"new_uuid": new_uuid, "old_id": row[0]}
        )

    # Делаем new_id NOT NULL
    op.alter_column('route_tariff', 'new_id', nullable=False)

    # Удаляем старую колонку
    op.drop_column('route_tariff', 'id')

    # Переименовываем new_id в id
    op.alter_column('route_tariff', 'new_id', new_column_name='id')

    # Устанавливаем как первичный ключ
    op.create_primary_key('pk_route_tariff', 'route_tariff', ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем добавленные колонки
    op.drop_column('shipment', 'total_cost')
    op.drop_column('shipment', 'cargo_type')

    # Возвращаем старый id
    op.add_column('route_tariff', sa.Column('old_id', sa.INTEGER(), nullable=True))

    # Копируем данные обратно (если возможно)
    # Здесь просто удаляем новую колонку, т.к. обратное преобразование UUID -> INT невозможно
    op.drop_column('route_tariff', 'id')
    op.alter_column('route_tariff', 'old_id', new_column_name='id')

    # ### end Alembic commands ###